platform :ios, '9.3'
target 'ProjectName' do
  use_frameworks!
  pod 'ViroReact', :path => '../node_modules/react-viro/ios/'
  pod 'ViroKit', :path => '../node_modules/react-viro/ios/dist/ViroRenderer/'
  post_install do |installer|
    system(". ./pod_post_install.sh")
end
end
